### ISSUE TITLE
NAD protocol

### ISSUE THREAD

**Issue by henriktorget** [KiboOst/php-NADC338#1]
Hey! 
Nice work. Sorry for contacting you this way, but i am very curious to where you found the documentation for how to communicate with the NAD C338.

I am considering buying this amp in order to control it with my own home automation system, but i will be writing it in Rust instead of php. And I would be more convinced to buy it if i found official documentation.

Thank you!

**Comment by KiboOst** [comment]
Hi, sorry being so late, didn't see your message.

There is isn't any official documentation about this. I did find the right way by downloading the NAD apk and decompile it to see how communication works.
Anyway, you can just replicate what my php script does in rust, I guess.
